### Variables
@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRkTFFQZ2ZINzh5dmM0OGs0MERWUyJ9.eyJpc3MiOiJodHRwczovL2Rldi1kam9obm5pZS5ldS5hdXRoMC5jb20vIiwic3ViIjoicW1SUm9yRDZ1Z2Y1WFBLMlBhUWtXcHQ2TlhzRWV4dXVAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vYXV0aDBpZGVudGl0eS5hcGkiLCJpYXQiOjE2ODI2MDYxOTEsImV4cCI6MTY4MjY5MjU5MSwiYXpwIjoicW1SUm9yRDZ1Z2Y1WFBLMlBhUWtXcHQ2TlhzRWV4dXUiLCJzY29wZSI6IkFkbWluIFN1cGVyQWRtaW4iLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJwZXJtaXNzaW9ucyI6WyJBZG1pbiIsIlN1cGVyQWRtaW4iXX0.XDCls481RhD7ZsQaCCCVyZDYxR2TTlSMCauvGC0JY0la1D-cA6IZ-D8JzPZrnE7a9MKzuVESf_hP4_Hcdj8-iPRKvPR1_hA__-IgAU8G-PApA0RFEWrGyTyhRAv2ax8NHylmKuRIFCFIRfTgM7mdJmSAKL7vEQ5iX0gZt1-Cv45y8cV4ZLCG9IMD_IrHrv6OiMOC076wZTKrjgoUL_xytJhGbiNu-u8LEHubYvLlsMRmkwfMcdSsZjhmYcYKVv1UGPsRcKoqAbzvpBnEsX9mXIW-45ZIBc84xYXgjyZ9V3NCKPMoWslC5rWhooOntGXYJ0tRlyh_dqrbvfNTx4Pl2g


### Unsecured GET
POST https://dev-djohnnie.eu.auth0.com/oauth/token
Content-Encoding-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=qmRRorD6ugf5XPK2PaQkWpt6NXsEexuu&client_secret=UzD3udpDZiVRwAas4SBOE5V7xOE9UQPhEmVMHu2AoPfbuhZcmKCdbFkMGDRRlmav&audience=https://auth0identity.api


### Secured GET
GET https://localhost:7052/secured
Authorization Bearer {{token}}